/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf,v 1.8 2007/09/14 12:57:34 dts12 Exp $
 */
#ifndef DEMO_MODULE_1_H
#define DEMO_MODULE_1_H

/* function declarations */
void init_demo_module_1(void);
Netsnmp_Node_Handler handle_me1SystemLoadAvg5min;
Netsnmp_Node_Handler handle_me1SystemLoadAvg1min;
Netsnmp_Node_Handler handle_me1SystemLoadAvg15min;

#endif /* DEMO_MODULE_1_H */
