/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf,v 1.8 2007/09/14 12:57:34 dts12 Exp $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "demo_module_1.h"
#include <glibtop/loadavg.h>

#define LOADAVG_1MIN  0
#define LOADAVG_5MIN  1
#define LOADAVG_15MIN 2

char* getLoadAvg(int timeAverage){
    glibtop_loadavg loadavg;
    char *data = malloc(30 * sizeof(char));
    glibtop_get_loadavg(&loadavg);
    sprintf(data, "%e", loadavg.loadavg[timeAverage]);

    return data;
}

/** Initializes the demo_module_1 module */
void
init_demo_module_1(void)
{
    static oid me1SystemLoadAvg1min_oid[] = { 1,3,6,1,4,1,4242,1,1,1 };
    static oid me1SystemLoadAvg5min_oid[] = { 1,3,6,1,4,1,4242,1,1,2 };
    static oid me1SystemLoadAvg15min_oid[] = { 1,3,6,1,4,1,4242,1,1,3 };

  DEBUGMSGTL(("demo_module_1", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("me1SystemLoadAvg1min", handle_me1SystemLoadAvg1min,
                               me1SystemLoadAvg1min_oid, OID_LENGTH(me1SystemLoadAvg1min_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("me1SystemLoadAvg5min", handle_me1SystemLoadAvg5min,
                               me1SystemLoadAvg5min_oid, OID_LENGTH(me1SystemLoadAvg5min_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("me1SystemLoadAvg15min", handle_me1SystemLoadAvg15min,
                               me1SystemLoadAvg15min_oid, OID_LENGTH(me1SystemLoadAvg15min_oid),
                               HANDLER_CAN_RONLY
        ));
}

int
handle_me1SystemLoadAvg1min(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */

    char* data;
    switch(reqinfo->mode) {

        case MODE_GET:
            data = getLoadAvg(LOADAVG_1MIN);
        snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR, (u_char *) data , strlen(data));
        free(data);
            break;


        default:
            /* we should never get here, so this is a really bad error */
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_me1SystemLoadAvg5min(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    char* data;
    switch(reqinfo->mode) {

        case MODE_GET:
            data = getLoadAvg(LOADAVG_5MIN);
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR, (u_char *) data , strlen(data));
            free(data);
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_me1SystemLoadAvg5min\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_me1SystemLoadAvg15min(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    char* data;
    switch(reqinfo->mode) {

        case MODE_GET:
            data = getLoadAvg(LOADAVG_15MIN);
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR, (u_char *) data , strlen(data));
            free(data);
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_me1SystemLoadAvg15min\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
