/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf,v 5.14.2.2 2007/05/09 08:13:01 dts12 Exp $
 */
#ifndef ME4FILETABLE_H
#define ME4FILETABLE_H

/* function declarations */
void init_me4FileTable(void);
void initialize_table_me4FileTable(void);
Netsnmp_Node_Handler me4FileTable_handler;
Netsnmp_First_Data_Point  me4FileTable_get_first_data_point;
Netsnmp_Next_Data_Point   me4FileTable_get_next_data_point;

int AddItem(u_long index, char *fileName);
int ChangeItem (int fileIndex, char* fileName);
char* GetFileName( int fIndex);
void demo4_load_tokens(const char *token, char *cptr);
int demo4_persist_data(int a, int b, void *c, void *d);
int demo4_post_read_config(int a, int b, void *c, void *d);

/* column number definitions for table me4FileTable */
       #define COLUMN_ME4FILEINDEX		1
       #define COLUMN_ME4FILENAME		2
       #define COLUMN_ME4FILESIZE		3
       #define COLUMN_ME4FILEPERM		4
#endif /* ME4FILETABLE_H */
