/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf,v 5.14.2.2 2007/05/09 08:13:01 dts12 Exp $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "demo_module_4.h"

#include <sys/types.h>
#include <sys/stat.h>
#include <stdio.h>
#include <errno.h>

#define DEMO4_CONF_FILE "_demo_module_4"
#define DEMO4_FILE      "demo4_file"
#define DEMO4_FILE1     "demo4_file1"
#define DEMO4_FILE2     "demo4_file2"
#define DEMO4_FILE3     "demo4_file3"
#define DEMO4_FILE4     "demo4_file4"

/*
 * FILENAME_MAX is the maximum permissible file name defined in param.h
 */

char            file1[FILENAME_MAX], file2[FILENAME_MAX], file3[FILENAME_MAX],
                file4[FILENAME_MAX];

char confFile[FILENAME_MAX];

void
demo4_load_tokens(const char *token, char *cptr);
int
demo4_post_read_config(int a, int b, void *c, void *d);
void
UpdateItem(u_long index, char *fileName);
/** Initializes the me4FileTable module */
void
init_demo_module_4(void)
{
    DEBUGMSGTL(("demo_module_4", "initialize_table_me4FileTable()\n"));
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_me4FileTable();
}

/** Initialize the me4FileTable table by defining its contents and how it's structured */
void
initialize_table_me4FileTable(void)
{
    static oid me4FileTable_oid[] = {1,3,6,1,4,1,4242,4,1,1};
    size_t me4FileTable_oid_len   = OID_LENGTH(me4FileTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    reg = netsnmp_create_handler_registration(
              "me4FileTable",     me4FileTable_handler,
              me4FileTable_oid, me4FileTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_UNSIGNED,  /* index: me4FileIndex */
                           0);
    table_info->min_column = 1;
    table_info->max_column = 4;

    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = me4FileTable_get_first_data_point;
    iinfo->get_next_data_point  = me4FileTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;

    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
    /*
     * These are the default files that are monitored by the module if there
     * is no persistent data (file names to be monitored). This is likely
     * during the first running on the module, when the .conf file does not
     * have any file related information.
     */

    strcpy(file1, "/etc/hosts");
    strcpy(file2, "/etc/group");
    strcpy(file3, "/etc/passwd");
    strcpy(file4, "/etc/crontab");


    /*
     * Register for tokens from demo_module_4.conf file. The names of the
     * tokens are demo4_file1,demo4_file2,demo4_file3,demo4_file4. The function
     * demo4_load_tokens is called whenever these 4 tokens are encountered in
     * demo_module_4.conf file.
     */

    char* user = getenv("USER");
    strcpy(confFile, user);
    strcat(confFile, DEMO4_CONF_FILE);
    confFile[strlen(DEMO4_CONF_FILE)+strlen(user)+1] = '\0';

    register_config_handler(confFile, DEMO4_FILE1,
                demo4_load_tokens, NULL, NULL);

    register_config_handler(confFile, DEMO4_FILE2,
                demo4_load_tokens, NULL, NULL);

    register_config_handler(confFile, DEMO4_FILE3,
                demo4_load_tokens, NULL, NULL);

    register_config_handler(confFile, DEMO4_FILE4,
                demo4_load_tokens, NULL, NULL);



    /*
     * Register for a callback when all the configuration files are read. The
     * callback function here is demo4_post_read_config
     */

    snmp_register_callback(SNMP_CALLBACK_LIBRARY, SNMP_CALLBACK_POST_READ_CONFIG,
               demo4_post_read_config, NULL);

}

    /* Typical data structure for a row entry */
struct me4FileTable_entry {
    /* Index values */
    u_long me4FileIndex;

    /* Column values */
    //u_long me4FileIndex;
    char me4FileName[255];
    char old_me4FileName[255];
    u_long me4FileSize;
    char me4FilePerm[255];

    /* Illustrate using a simple linked list */
    int   valid;
    struct me4FileTable_entry *next;
};

struct me4FileTable_entry  *me4FileTable_head;

/* create a new row in the (unsorted) table */
struct me4FileTable_entry *
me4FileTable_createEntry(
                 u_long  me4FileIndex
                ) {
    struct me4FileTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct me4FileTable_entry);
    if (!entry)
        return NULL;

    entry->me4FileIndex = me4FileIndex;
    entry->next = me4FileTable_head;
    me4FileTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
me4FileTable_removeEntry( struct me4FileTable_entry *entry ) {
    struct me4FileTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = me4FileTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        me4FileTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}



/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
me4FileTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = me4FileTable_head;
    return me4FileTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
me4FileTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct me4FileTable_entry *entry = (struct me4FileTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_value( idx, (u_char*) &entry->me4FileIndex, sizeof(entry->me4FileIndex) );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}

/** handles requests for the me4FileTable table */
int
me4FileTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct me4FileTable_entry          *table_entry;

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct me4FileTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

           if (table_entry == NULL) {
               return;
           }

           struct stat fAttrib;
           if (stat(table_entry->me4FileName, &fAttrib) != -1) {
                table_entry->me4FileSize = fAttrib.st_size;
                sprintf(table_entry->me4FilePerm, "%o", fAttrib.st_mode & 0777);
           } else {
                table_entry->me4FileSize = 0;
                sprintf(table_entry->me4FilePerm, "%d", -1);
           }

           switch (table_info->colnum) {
            case COLUMN_ME4FILEINDEX:
                snmp_set_var_typed_value( request->requestvb, ASN_UNSIGNED,
                                          (u_char *) &table_entry->me4FileIndex,
                                          sizeof(table_entry->me4FileIndex));
                break;
            case COLUMN_ME4FILENAME:
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          (u_char *) table_entry->me4FileName,
                                          strlen(table_entry->me4FileName));
                break;
            case COLUMN_ME4FILESIZE:
                snmp_set_var_typed_value( request->requestvb, ASN_UNSIGNED,
                                          (u_char *) &table_entry->me4FileSize,
                                          sizeof(table_entry->me4FileSize));
                break;
            case COLUMN_ME4FILEPERM:
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          (u_char *) table_entry->me4FilePerm,
                                          strlen(table_entry->me4FilePerm));
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            table_entry = (struct me4FileTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            if (!table_entry) {
 	        netsnmp_set_request_error(reqinfo, request,
					  SNMP_ERR_NOCREATION);
                return SNMP_ERR_NOERROR;
            }
            switch (table_info->colnum) {
            case COLUMN_ME4FILENAME:
                if ( request->requestvb->type != ASN_OCTET_STR ) {
                    netsnmp_set_request_error( reqinfo, request,
                                               SNMP_ERR_WRONGTYPE );
                    return SNMP_ERR_NOERROR;
                }
                /* Also may need to check size/value */
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        for (request=requests; request; request=request->next) {
            table_entry = (struct me4FileTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            switch (table_info->colnum) {
            case COLUMN_ME4FILENAME:
                //if ( !table_row ) {
                if ( !table_entry ) {
                    //table_row = me4FileTable_createEntry(
                    //    , table_info->indexes->val.YYY
                    //    );
                    netsnmp_table_row* table_row = (netsnmp_table_row*) me4FileTable_createEntry(
                        (u_long) table_info->indexes->val.integer
                        );
                    if (table_row) {
                        //netsnmp_insert_table_row( request, table_row );
                        netsnmp_insert_iterator_context(request, table_row);
                    } else {
                        netsnmp_set_request_error( reqinfo, request,
                                                   SNMP_ERR_RESOURCEUNAVAILABLE );
                        return SNMP_ERR_NOERROR;
                    }
                }
                break;
            }
        }
        break;

    case MODE_SET_FREE:
        for (request=requests; request; request=request->next) {
            table_entry = (struct me4FileTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            switch (table_info->colnum) {
            case COLUMN_ME4FILENAME:
                if ( table_entry && !table_entry->valid ) {
                    //me4FileTable_removeEntry(table_data, table_row );
                    me4FileTable_removeEntry(table_entry);
                }
                break;
            }
        }
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_entry = (struct me4FileTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            switch (table_info->colnum) {
            case COLUMN_ME4FILENAME:
                /* Need to save old 'table_entry->me4FileName' value.
                   May need to use 'memcpy' */
                //table_entry->old_me4FileName = table_entry->me4FileName;
                //table_entry->me4FileName     = request->requestvb->val.YYY;
                strcpy(table_entry->old_me4FileName, (char*) table_entry->me4FileName);
                memcpy(table_entry->me4FileName, (char*) request->requestvb->val.string,
                       request->requestvb->val_len+1);
                table_entry->me4FileName[request->requestvb->val_len] = '\0';
                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            table_entry = (struct me4FileTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            switch (table_info->colnum) {
            case COLUMN_ME4FILENAME:
                if ( table_entry && !table_entry->valid ) {
                    //me4FileTable_removeEntry(table_data, table_row );
                    me4FileTable_removeEntry(table_entry);
                } else {
                    /* Need to restore old 'table_entry->me4FileName' value.
                       May need to use 'memcpy' */
                    //table_entry->me4FileName = table_entry->old_me4FileName;
                    strcpy(table_entry->me4FileName, (char*) table_entry->old_me4FileName);
                }
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        for (request=requests; request; request=request->next) {
            table_entry = (struct me4FileTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            switch (table_info->colnum) {
            case COLUMN_ME4FILENAME:
                if ( table_entry && !table_entry->valid ) {
                    table_entry->valid = 1;
                }
                char            filebuf[255];
                snprintf(&filebuf[0], FILENAME_MAX, "%s%d %s", DEMO4_FILE,
                         table_entry->me4FileIndex, table_entry->me4FileName);
                UpdateItem(table_entry->me4FileIndex, table_entry->me4FileName);
                read_config_store(confFile, &filebuf[0]);
            }
        }
        break;
    }
    return SNMP_ERR_NOERROR;
}

void
demo4_load_tokens(const char *token, char *cptr)
{

    if (strcmp(token, DEMO4_FILE1) == 0) {
        strcpy(file1, cptr);
    } else if (strcmp(token, DEMO4_FILE2) == 0) {
        strcpy(file2, cptr);
    } else if (strcmp(token, DEMO4_FILE3) == 0) {
        strcpy(file3, cptr);
    } else if (strcmp(token, DEMO4_FILE4) == 0) {
        strcpy(file4, cptr);
    } else {
        /* Do Nothing */
    }
    return;

}

/*
 * Function that persists file information. This is called by the agent
 * whenever data needs to be persisted.
 */

int
demo4_persist_data(int a, int b, void *c, void *d)
{

    char filebuf[300];
    char tmp[100];


    sprintf(filebuf, "%s %s", DEMO4_FILE1, file1);
    read_config_store(confFile, filebuf);

    sprintf(tmp, "stored '%s'\n", filebuf);
    DEBUGMSGTL(("demo_module_4", tmp));


    sprintf(filebuf, "%s %s", DEMO4_FILE2, file2);
    read_config_store(confFile, filebuf);

    sprintf(tmp, "stored '%s'\n", filebuf);
    DEBUGMSGTL(("demo_module_4", tmp));


    sprintf(filebuf, "%s %s", DEMO4_FILE3, file3);
    read_config_store(confFile, filebuf);

    sprintf(tmp, "stored '%s'\n", filebuf);
    DEBUGMSGTL(("demo_module_4", tmp));


    sprintf(filebuf, "%s %s", DEMO4_FILE4, file4);
    read_config_store(confFile, filebuf);

    sprintf(tmp, "stored '%s'\n", filebuf);
    DEBUGMSGTL(("demo_module_4", tmp));

}

/* Function to add a fileName to the linked list of files */

void
UpdateItem(u_long fileIndex, char *fileName)
{
    struct me4FileTable_entry  *tempp = me4FileTable_head;

    while (tempp != NULL) {
        if (tempp->me4FileIndex == fileIndex) {
            strcpy(tempp->me4FileName, fileName);
            switch(fileIndex) {
            case 1:
	      strcpy(file1, fileName);
              break;
            case 2:
              strcpy(file2, fileName);
              break;
            case 3:
              strcpy(file3, fileName);
              break;
            case 4:
              strcpy(file4, fileName);
              break;
	    }
	    return;
	}
        tempp = tempp->next;
    }
}

int
AddItem(u_long index, char *fileName)
{

    struct me4FileTable_entry  *fprt;
    struct stat     fAttrib;    /* Need to check if memory is valid */

    if (!fileName || !strlen(fileName)) {
        return FALSE;
    }
    fprt = me4FileTable_createEntry(index);

    if (stat(fileName, &fAttrib) == -1) {
    /*
     * Unable to get the file information, it could be more than file not
     * exists if (errno == ENOENT) { return FALSE; } return FALSE;
     */
        DEBUGMSGTL(("demo_module_4", "Can't access the file %s", fileName));
    }

    strcpy(fprt->me4FileName, fileName);
    fprt->me4FileSize = fAttrib.st_size;
    sprintf(fprt->me4FilePerm, "%d", fAttrib.st_mode);

    return TRUE;
}

/*
 * Callback function that is called after all the configuration files are
 * read by the agent. See init_demo_module_4 function to see how this
 * callback is specified.
 *
 * When this function is called, any persistent file information would have been
 * read into the module. These files are added to the file list.
 *
 * The callback function to persist data (demo4_persist_data) is registered.
 */

int
demo4_post_read_config(int a, int b, void *c, void *d)
{

    if (!AddItem(1, file1)) {
        snmp_log(LOG_ERR, "Failed to add instance in init_demo_module_4\n");
    }
    if (!AddItem(2, file2)) {
        snmp_log(LOG_ERR, "Failed to add instance in init_demo_module_4\n");
    }
    if (!AddItem(3, file3)) {
        snmp_log(LOG_ERR, "Failed to add instance in init_demo_module_4\n");
    }
    if (!AddItem(4, file4)) {
        snmp_log(LOG_ERR, "Failed to add instance in init_demo_module_4\n");
    }


    snmp_register_callback(SNMP_CALLBACK_LIBRARY, SNMP_CALLBACK_STORE_DATA,
               demo4_persist_data, NULL);


}
