/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf,v 5.14.2.2 2007/05/09 08:13:01 dts12 Exp $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "demo_module_2.h"
#include <sys/stat.h>

struct me2FileTable_entry *
me2FileTable_addEntry(int fileIndex, char* fileName);

/** Initializes the me2FileTable module */
void
init_demo_module_2(void)
{
    DEBUGMSGTL(("demo_module_2", "initialize_table_me2FileTable()\n"));
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_me2FileTable();
}

/** Initialize the me2FileTable table by defining its contents and how it's structured */
void
initialize_table_me2FileTable(void)
{
    static oid me2FileTable_oid[] = {1,3,6,1,4,1,4242,2,1,1};
    size_t me2FileTable_oid_len   = OID_LENGTH(me2FileTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    reg = netsnmp_create_handler_registration(
              "me2FileTable",     me2FileTable_handler,
              me2FileTable_oid, me2FileTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_UNSIGNED,  /* index: me2FileIndex */
                           0);
    table_info->min_column = 1;
    table_info->max_column = 4;

    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = me2FileTable_get_first_data_point;
    iinfo->get_next_data_point  = me2FileTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;

    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
    if (!me2FileTable_addEntry(1, "/etc/hosts")) {
      snmp_log(LOG_ERR, "Failed to add instance in init_demo_module_2\n");
    } else {
      DEBUGMSGTL(("demo_module_2", "Added instance in init_demo_module_2\n"));
    }
    if (!me2FileTable_addEntry(2, "/etc/passwd")) {
      snmp_log(LOG_ERR, "Failed to add instance in init_demo_module_2\n");
    } else {
      DEBUGMSGTL(("demo_module_2", "Added instance in init_demo_module_2\n"));
    }

}

// Modificaciones sobre el codigo generado por mib2c
    /* Typical data structure for a row entry */
struct me2FileTable_entry {
    /* Index values */
    u_long me2FileIndex;

    /* Column values */
    //u_long me2FileIndex;
    char me2FileName[255];
    char old_me2FileName[255];
    u_long me2FileSize;
    char me2FilePerm[255];

    /* Illustrate using a simple linked list */
    int   valid;
    struct me2FileTable_entry *next;
};

struct me2FileTable_entry  *me2FileTable_head;

/* create a new row in the (unsorted) table */
struct me2FileTable_entry *
me2FileTable_createEntry(
                 u_long  me2FileIndex
                ) {
    struct me2FileTable_entry *entry;

    // Modificacion sobre el codigo generado por mib2c
    entry = SNMP_MALLOC_TYPEDEF(struct me2FileTable_entry);
    if (!entry)
        return NULL;

    entry->me2FileIndex = me2FileIndex;
    entry->next = me2FileTable_head;
    strcpy(entry->me2FileName, "");
    strcpy(entry->old_me2FileName, "");
    strcpy(entry->me2FilePerm, "");
    entry->valid = 0;
    entry->me2FileSize = 0;
    me2FileTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
me2FileTable_removeEntry( struct me2FileTable_entry *entry ) {
    struct me2FileTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = me2FileTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        me2FileTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}

int setFileProperties(char* filePerm, u_long* size, const char* fileName) {

    struct stat fAttrib;  /* Need to check if memory is valid */
    if (fileName && strlen(fileName)) {
        if (stat(fileName, &fAttrib) != -1) {
            sprintf(filePerm, "%o", fAttrib.st_mode & 0777);
            *size = fAttrib.st_size;
            return TRUE;
        } else {
            DEBUGMSGTL(("demo_module_2", "Can't access the file %s", fileName));
        }
    }
    strcpy(filePerm, "");
    return FALSE;
}

/* add a row in the table */
struct me2FileTable_entry *
me2FileTable_addEntry(int fileIndex, char* fileName) {
    struct me2FileTable_entry *entry;

    if (!fileName || !strlen(fileName)) {
        return FALSE;
    }

    entry = SNMP_MALLOC_TYPEDEF(struct me2FileTable_entry);
    if (!entry)
        return FALSE;

    entry->me2FileIndex = fileIndex;
    strcpy(entry->me2FileName, fileName);
    setFileProperties(entry->me2FilePerm, &entry->me2FileSize, fileName);
    entry->next = me2FileTable_head;
    me2FileTable_head = entry;

    return entry;
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
me2FileTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = me2FileTable_head;
    return me2FileTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
me2FileTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct me2FileTable_entry *entry = (struct me2FileTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        // Modificacion sobre el codigo generado por mib2c
        snmp_set_var_value( idx, (u_char *) &entry->me2FileIndex, sizeof(entry->me2FileIndex) );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        // Linea de codigo anadida al codigo generado por mib2c
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the me2FileTable table */
int
me2FileTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct me2FileTable_entry          *table_entry;

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct me2FileTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            if (table_entry == NULL) {
                return;
            }

            setFileProperties(table_entry->me2FilePerm, &table_entry->me2FileSize,
                table_entry->me2FileName);
            switch (table_info->colnum) {
            case COLUMN_ME2FILEINDEX:
                snmp_set_var_typed_value( request->requestvb, ASN_UNSIGNED,
                                          (u_char*) &table_entry->me2FileIndex,
                                          sizeof(table_entry->me2FileIndex));
                break;
            case COLUMN_ME2FILENAME:
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          (u_char*) table_entry->me2FileName,
                                          strlen(table_entry->me2FileName));
                break;
            case COLUMN_ME2FILESIZE:
                snmp_set_var_typed_value( request->requestvb, ASN_UNSIGNED,
                                          (u_char*) &table_entry->me2FileSize,
                                          sizeof(table_entry->me2FileSize));
                break;
            case COLUMN_ME2FILEPERM:
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          (u_char*) table_entry->me2FilePerm,
                                          strlen(table_entry->me2FilePerm));
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            table_entry = (struct me2FileTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            switch (table_info->colnum) {
            case COLUMN_ME2FILENAME:
                if ( request->requestvb->type != ASN_OCTET_STR ) {
                    netsnmp_set_request_error( reqinfo, request,
                                               SNMP_ERR_WRONGTYPE );
                    return SNMP_ERR_NOERROR;
                }
                /* Also may need to check size/value */
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        for (request=requests; request; request=request->next) {
            table_entry = (struct me2FileTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            switch (table_info->colnum) {
            case COLUMN_ME2FILENAME:
                // Modificaciones sobre el codigo generado por mib2c
                //if ( !table_row ) {
                if ( !table_entry ) {
                    //table_row = me2FileTable_createEntry(
                    //    , table_info->indexes->val.YYY
                    //    );
                    netsnmp_table_row* table_row = (netsnmp_table_row*) me2FileTable_createEntry(
                        (ulong) *table_info->indexes->val.integer
                        );
                    if (table_row) {
                        //netsnmp_insert_table_row( request, table_row );
                        netsnmp_insert_iterator_context(request, table_row);
                    } else {
                        netsnmp_set_request_error( reqinfo, request,
                                                   SNMP_ERR_RESOURCEUNAVAILABLE );
                        return SNMP_ERR_NOERROR;
                    }
                }
                break;
            }
        }
        break;

    case MODE_SET_FREE:
        for (request=requests; request; request=request->next) {
            table_entry = (struct me2FileTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            switch (table_info->colnum) {
            case COLUMN_ME2FILENAME:
                if ( table_entry && !table_entry->valid ) {
                    // Modificacion sobre el codigo generado por mib2c
                    //me2FileTable_removeEntry(table_data, table_row );
                    me2FileTable_removeEntry(table_entry);
                }
                break;
            }
        }
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_entry = (struct me2FileTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            switch (table_info->colnum) {
            case COLUMN_ME2FILENAME:
                /* Need to save old 'table_entry->me2FileName' value.
                   May need to use 'memcpy' */
                // Modificaciones sobre el codigo generado por mib2c
                //table_entry->old_me2FileName = table_entry->me2FileName;
                //table_entry->me2FileName     = request->requestvb->val.string;
                strcpy(table_entry->old_me2FileName, (char*) table_entry->me2FileName);
                memcpy(table_entry->me2FileName, (char*) request->requestvb->val.string,
                       request->requestvb->val_len+1);
                table_entry->me2FileName[request->requestvb->val_len] = '\0';
                setFileProperties(table_entry->me2FilePerm, &table_entry->me2FileSize,
                    table_entry->me2FileName);
                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            table_entry = (struct me2FileTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            switch (table_info->colnum) {
            case COLUMN_ME2FILENAME:
                // Modificaciones sobre el codigo generado por mib2c
                if ( table_entry && !table_entry->valid ) {
                    //me2FileTable_removeEntry(table_data, table_row );
                    me2FileTable_removeEntry( table_entry );
                } else {
                    /* Need to restore old 'table_entry->me2FileName' value.
                       May need to use 'memcpy' */
                    //table_entry->me2FileName = table_entry->old_me2FileName;
                    strcpy(table_entry->me2FileName, (char*) table_entry->old_me2FileName);
                }
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        for (request=requests; request; request=request->next) {
            table_entry = (struct me2FileTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);

            switch (table_info->colnum) {
            case COLUMN_ME2FILENAME:
                if ( table_entry && !table_entry->valid ) {
                    table_entry->valid = 1;
                }
            }
        }
        break;
    }
    return SNMP_ERR_NOERROR;
}
