/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf,v 5.14.2.2 2007/05/09 08:13:01 dts12 Exp $
 */
#ifndef ME2FILETABLE_H
#define ME2FILETABLE_H

/* function declarations */
void init_me2FileTable(void);
void initialize_table_me2FileTable(void);
Netsnmp_Node_Handler me2FileTable_handler;
Netsnmp_First_Data_Point  me2FileTable_get_first_data_point;
Netsnmp_Next_Data_Point   me2FileTable_get_next_data_point;

/* column number definitions for table me2FileTable */
       #define COLUMN_ME2FILEINDEX		1
       #define COLUMN_ME2FILENAME		2
       #define COLUMN_ME2FILESIZE		3
       #define COLUMN_ME2FILEPERM		4
#endif /* ME2FILETABLE_H */
