/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 15999 2007-03-25 22:32:02Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "me2FileTable.h"

/** Initializes the me2FileTable module */
void
init_me2FileTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_me2FileTable();
}

  # Determine the first/last column names

/** Initialize the me2FileTable table by defining its contents and how it's structured */
void
initialize_table_me2FileTable(void)
{
    static oid me2FileTable_oid[] = {1,3,6,1,4,1,4242,2,1,1};
    size_t me2FileTable_oid_len   = OID_LENGTH(me2FileTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    reg = netsnmp_create_handler_registration(
              "me2FileTable",     me2FileTable_handler,
              me2FileTable_oid, me2FileTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_UNSIGNED,  /* index: me2FileIndex */
                           0);
    table_info->min_column = COLUMN_ME2FILEINDEX;
    table_info->max_column = COLUMN_ME2FILEPERM;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = me2FileTable_get_first_data_point;
    iinfo->get_next_data_point  = me2FileTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
}

    /* Typical data structure for a row entry */
struct me2FileTable_entry {
    /* Index values */
    u_long me2FileIndex;

    /* Column values */
    u_long me2FileIndex;
    char me2FileName[NNN];
    size_t me2FileName_len;
    char old_me2FileName[NNN];
    size_t old_me2FileName_len;
    u_long me2FileSize;
    char me2FilePerm[NNN];
    size_t me2FilePerm_len;

    /* Illustrate using a simple linked list */
    int   valid;
    struct me2FileTable_entry *next;
};

struct me2FileTable_entry  *me2FileTable_head;

/* create a new row in the (unsorted) table */
struct me2FileTable_entry *
me2FileTable_createEntry(
                 u_long  me2FileIndex,
                ) {
    struct me2FileTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct me2FileTable_entry);
    if (!entry)
        return NULL;

    entry->me2FileIndex = me2FileIndex;
    entry->next = me2FileTable_head;
    me2FileTable_head = entry;
    return entry;
}

/* remove a row from the table */
void
me2FileTable_removeEntry( struct me2FileTable_entry *entry ) {
    struct me2FileTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = me2FileTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        me2FileTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
me2FileTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = me2FileTable_head;
    return me2FileTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
me2FileTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct me2FileTable_entry *entry = (struct me2FileTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_UNSIGNED, entry->me2FileIndex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the me2FileTable table */
int
me2FileTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct me2FileTable_entry          *table_entry;

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct me2FileTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_ME2FILEINDEX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->me2FileIndex);
                break;
            case COLUMN_ME2FILENAME:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                 (u_char*)table_entry->me2FileName,
                                          table_entry->me2FileName_len);
                break;
            case COLUMN_ME2FILESIZE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->me2FileSize);
                break;
            case COLUMN_ME2FILEPERM:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                 (u_char*)table_entry->me2FilePerm,
                                          table_entry->me2FilePerm_len);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            table_entry = (struct me2FileTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_ME2FILENAME:
	        /* or possiblc 'netsnmp_check_vb_type_and_size' */
                ret = netsnmp_check_vb_type_and_max_size(
                          request->requestvb, ASN_OCTET_STR, sizeof(table_entry->me2FileName));
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        for (request=requests; request; request=request->next) {
            table_entry = (struct me2FileTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_ME2FILENAME:
                if ( !table_row ) {
                    table_row = me2FileTable_createEntry(
                        , *table_info->indexes->val.integer
                        );
                    if (table_row) {
                        netsnmp_insert_iterator_context( request, table_row );
                    } else {
                        netsnmp_set_request_error( reqinfo, request,
                                                   SNMP_ERR_RESOURCEUNAVAILABLE );
                        return SNMP_ERR_NOERROR;
                    }
                }
                break;
            }
        }
        break;

    case MODE_SET_FREE:
        for (request=requests; request; request=request->next) {
            table_entry = (struct me2FileTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_ME2FILENAME:
                if ( table_entry && !table_entry->valid ) {
                    me2FileTable_removeEntry(table_data, table_row );
                }
                break;
            }
        }
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_entry = (struct me2FileTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_ME2FILENAME:
                memcpy( table_entry->old_me2FileName,
                        table_entry->me2FileName,
                        sizeof(table_entry->me2FileName));
                table_entry->old_me2FileName_len =
                        table_entry->me2FileName_len;
                memset( table_entry->me2FileName, 0,
                        sizeof(table_entry->me2FileName));
                memcpy( table_entry->me2FileName,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->me2FileName_len =
                        request->requestvb->val_len;
                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            table_entry = (struct me2FileTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_ME2FILENAME:
                if ( table_entry && !table_entry->valid ) {
                    me2FileTable_removeEntry(table_data, table_row );
                } else {
                    memcpy( table_entry->me2FileName,
                            table_entry->old_me2FileName,
                            sizeof(table_entry->me2FileName));
                    memset( table_entry->old_me2FileName, 0,
                            sizeof(table_entry->me2FileName));
                    table_entry->me2FileName_len =
                            table_entry->old_me2FileName_len;
                }
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        for (request=requests; request; request=request->next) {
            table_entry = (struct me2FileTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_ME2FILENAME:
                if ( table_entry && !table_entry->valid ) {
                    table_entry->valid = 1;
                }
            }
        }
        break;
    }
    return SNMP_ERR_NOERROR;
}
