/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf,v 1.8 2007/09/14 12:57:34 dts12 Exp $
 */
#ifndef ME3LOADGROUP_H
#define ME3LOADGROUP_H

#define OK 0
#define ERROR 1

/* function declarations */
void init_me3LoadGroup(void);
Netsnmp_Node_Handler handle_me3SystemLoadAvg1min;
Netsnmp_Node_Handler handle_me3SystemLoadAvg5min;
Netsnmp_Node_Handler handle_me3SystemLoadAvg15min;
Netsnmp_Node_Handler handle_statusOID;
Netsnmp_Node_Handler handle_objectStatus;
Netsnmp_Node_Handler handle_eventDescription;

#endif /* ME3LOADGROUP_H */
