//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3607
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Es.Udc.DotNet.Betbook.Model", "FK_CommentUserId", "User", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Es.Udc.DotNet.Betbook.Model.User), "Comment", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.Betbook.Model.Comment))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Es.Udc.DotNet.Betbook.Model", "FK_Languages", "Languages", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Es.Udc.DotNet.Betbook.Model.Languages), "Countries", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.Betbook.Model.Countries))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Es.Udc.DotNet.Betbook.Model", "FK_FavouriteUserId", "User", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Es.Udc.DotNet.Betbook.Model.User), "Favourite", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.Betbook.Model.Favourite))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Es.Udc.DotNet.Betbook.Model", "FK_GroupCreatorId", "User", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Es.Udc.DotNet.Betbook.Model.User), "Group", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.Betbook.Model.Group))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Es.Udc.DotNet.Betbook.Model", "FK_RecommendationUserId", "User", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Es.Udc.DotNet.Betbook.Model.User), "Recommendation", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.Betbook.Model.Recommendation))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Es.Udc.DotNet.Betbook.Model", "CommentTags", "Comment", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.Betbook.Model.Comment), "Tag", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.Betbook.Model.Tag))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Es.Udc.DotNet.Betbook.Model", "GroupUsers", "Group", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.Betbook.Model.Group), "User", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.Betbook.Model.User))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("Es.Udc.DotNet.Betbook.Model", "RecommendationGroups", "Group", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.Betbook.Model.Group), "Recommendation", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Es.Udc.DotNet.Betbook.Model.Recommendation))]

// Original file name:
// Generation date: 22/06/2010 17:42:07
namespace Es.Udc.DotNet.Betbook.Model
{
    
    /// <summary>
    /// There are no comments for BetbookEntitiesContainer in the schema.
    /// </summary>
    public partial class BetbookEntitiesContainer : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new BetbookEntitiesContainer object using the connection string found in the 'BetbookEntitiesContainer' section of the application configuration file.
        /// </summary>
        public BetbookEntitiesContainer() : 
                base("name=BetbookEntitiesContainer", "BetbookEntitiesContainer")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new BetbookEntitiesContainer object.
        /// </summary>
        public BetbookEntitiesContainer(string connectionString) : 
                base(connectionString, "BetbookEntitiesContainer")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new BetbookEntitiesContainer object.
        /// </summary>
        public BetbookEntitiesContainer(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "BetbookEntitiesContainer")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Comment in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Comment> Comment
        {
            get
            {
                if ((this._Comment == null))
                {
                    this._Comment = base.CreateQuery<Comment>("[Comment]");
                }
                return this._Comment;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Comment> _Comment;
        /// <summary>
        /// There are no comments for Countries in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Countries> Countries
        {
            get
            {
                if ((this._Countries == null))
                {
                    this._Countries = base.CreateQuery<Countries>("[Countries]");
                }
                return this._Countries;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Countries> _Countries;
        /// <summary>
        /// There are no comments for Favourite in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Favourite> Favourite
        {
            get
            {
                if ((this._Favourite == null))
                {
                    this._Favourite = base.CreateQuery<Favourite>("[Favourite]");
                }
                return this._Favourite;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Favourite> _Favourite;
        /// <summary>
        /// There are no comments for Group in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Group> Group
        {
            get
            {
                if ((this._Group == null))
                {
                    this._Group = base.CreateQuery<Group>("[Group]");
                }
                return this._Group;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Group> _Group;
        /// <summary>
        /// There are no comments for Languages in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Languages> Languages
        {
            get
            {
                if ((this._Languages == null))
                {
                    this._Languages = base.CreateQuery<Languages>("[Languages]");
                }
                return this._Languages;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Languages> _Languages;
        /// <summary>
        /// There are no comments for Recommendation in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Recommendation> Recommendation
        {
            get
            {
                if ((this._Recommendation == null))
                {
                    this._Recommendation = base.CreateQuery<Recommendation>("[Recommendation]");
                }
                return this._Recommendation;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Recommendation> _Recommendation;
        /// <summary>
        /// There are no comments for Tag in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Tag> Tag
        {
            get
            {
                if ((this._Tag == null))
                {
                    this._Tag = base.CreateQuery<Tag>("[Tag]");
                }
                return this._Tag;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Tag> _Tag;
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<User> User
        {
            get
            {
                if ((this._User == null))
                {
                    this._User = base.CreateQuery<User>("[User]");
                }
                return this._User;
            }
        }
        private global::System.Data.Objects.ObjectQuery<User> _User;
        /// <summary>
        /// There are no comments for Comment in the schema.
        /// </summary>
        public void AddToComment(Comment comment)
        {
            base.AddObject("Comment", comment);
        }
        /// <summary>
        /// There are no comments for Countries in the schema.
        /// </summary>
        public void AddToCountries(Countries countries)
        {
            base.AddObject("Countries", countries);
        }
        /// <summary>
        /// There are no comments for Favourite in the schema.
        /// </summary>
        public void AddToFavourite(Favourite favourite)
        {
            base.AddObject("Favourite", favourite);
        }
        /// <summary>
        /// There are no comments for Group in the schema.
        /// </summary>
        public void AddToGroup(Group group)
        {
            base.AddObject("Group", group);
        }
        /// <summary>
        /// There are no comments for Languages in the schema.
        /// </summary>
        public void AddToLanguages(Languages languages)
        {
            base.AddObject("Languages", languages);
        }
        /// <summary>
        /// There are no comments for Recommendation in the schema.
        /// </summary>
        public void AddToRecommendation(Recommendation recommendation)
        {
            base.AddObject("Recommendation", recommendation);
        }
        /// <summary>
        /// There are no comments for Tag in the schema.
        /// </summary>
        public void AddToTag(Tag tag)
        {
            base.AddObject("Tag", tag);
        }
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        public void AddToUser(User user)
        {
            base.AddObject("User", user);
        }
    }
    /// <summary>
    /// There are no comments for Es.Udc.DotNet.Betbook.Model.Comment in the schema.
    /// </summary>
    /// <KeyProperties>
    /// commentId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Es.Udc.DotNet.Betbook.Model", Name="Comment")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Comment : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Comment object.
        /// </summary>
        /// <param name="commentId">Initial value of commentId.</param>
        /// <param name="text">Initial value of text.</param>
        /// <param name="date">Initial value of date.</param>
        /// <param name="eventId">Initial value of eventId.</param>
        public static Comment CreateComment(long commentId, string text, global::System.DateTime date, long eventId)
        {
            Comment comment = new Comment();
            comment.commentId = commentId;
            comment.text = text;
            comment.date = date;
            comment.eventId = eventId;
            return comment;
        }
        /// <summary>
        /// There are no comments for Property commentId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long commentId
        {
            get
            {
                return this._commentId;
            }
            set
            {
                this.OncommentIdChanging(value);
                this.ReportPropertyChanging("commentId");
                this._commentId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("commentId");
                this.OncommentIdChanged();
            }
        }
        private long _commentId;
        partial void OncommentIdChanging(long value);
        partial void OncommentIdChanged();
        /// <summary>
        /// There are no comments for Property text in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string text
        {
            get
            {
                return this._text;
            }
            set
            {
                this.OntextChanging(value);
                this.ReportPropertyChanging("text");
                this._text = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("text");
                this.OntextChanged();
            }
        }
        private string _text;
        partial void OntextChanging(string value);
        partial void OntextChanged();
        /// <summary>
        /// There are no comments for Property date in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime date
        {
            get
            {
                return this._date;
            }
            set
            {
                this.OndateChanging(value);
                this.ReportPropertyChanging("date");
                this._date = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("date");
                this.OndateChanged();
            }
        }
        private global::System.DateTime _date;
        partial void OndateChanging(global::System.DateTime value);
        partial void OndateChanged();
        /// <summary>
        /// There are no comments for Property eventId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long eventId
        {
            get
            {
                return this._eventId;
            }
            set
            {
                this.OneventIdChanging(value);
                this.ReportPropertyChanging("eventId");
                this._eventId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("eventId");
                this.OneventIdChanged();
            }
        }
        private long _eventId;
        partial void OneventIdChanging(long value);
        partial void OneventIdChanged();
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.Betbook.Model", "FK_CommentUserId", "User")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public User User
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("Es.Udc.DotNet.Betbook.Model.FK_CommentUserId", "User").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("Es.Udc.DotNet.Betbook.Model.FK_CommentUserId", "User").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<User> UserReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("Es.Udc.DotNet.Betbook.Model.FK_CommentUserId", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<User>("Es.Udc.DotNet.Betbook.Model.FK_CommentUserId", "User", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Tag in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.Betbook.Model", "CommentTags", "Tag")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Tag> Tag
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Tag>("Es.Udc.DotNet.Betbook.Model.CommentTags", "Tag");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Tag>("Es.Udc.DotNet.Betbook.Model.CommentTags", "Tag", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Es.Udc.DotNet.Betbook.Model.Countries in the schema.
    /// </summary>
    /// <KeyProperties>
    /// countryCode
    /// languageCode
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Es.Udc.DotNet.Betbook.Model", Name="Countries")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Countries : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Countries object.
        /// </summary>
        /// <param name="countryCode">Initial value of countryCode.</param>
        /// <param name="countryName">Initial value of countryName.</param>
        /// <param name="languageCode">Initial value of languageCode.</param>
        public static Countries CreateCountries(string countryCode, string countryName, string languageCode)
        {
            Countries countries = new Countries();
            countries.countryCode = countryCode;
            countries.countryName = countryName;
            countries.languageCode = languageCode;
            return countries;
        }
        /// <summary>
        /// There are no comments for Property countryCode in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string countryCode
        {
            get
            {
                return this._countryCode;
            }
            set
            {
                this.OncountryCodeChanging(value);
                this.ReportPropertyChanging("countryCode");
                this._countryCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("countryCode");
                this.OncountryCodeChanged();
            }
        }
        private string _countryCode;
        partial void OncountryCodeChanging(string value);
        partial void OncountryCodeChanged();
        /// <summary>
        /// There are no comments for Property countryName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string countryName
        {
            get
            {
                return this._countryName;
            }
            set
            {
                this.OncountryNameChanging(value);
                this.ReportPropertyChanging("countryName");
                this._countryName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("countryName");
                this.OncountryNameChanged();
            }
        }
        private string _countryName;
        partial void OncountryNameChanging(string value);
        partial void OncountryNameChanged();
        /// <summary>
        /// There are no comments for Property languageCode in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string languageCode
        {
            get
            {
                return this._languageCode;
            }
            set
            {
                this.OnlanguageCodeChanging(value);
                this.ReportPropertyChanging("languageCode");
                this._languageCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("languageCode");
                this.OnlanguageCodeChanged();
            }
        }
        private string _languageCode;
        partial void OnlanguageCodeChanging(string value);
        partial void OnlanguageCodeChanged();
        /// <summary>
        /// There are no comments for Languages in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.Betbook.Model", "FK_Languages", "Languages")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Languages Languages
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Languages>("Es.Udc.DotNet.Betbook.Model.FK_Languages", "Languages").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Languages>("Es.Udc.DotNet.Betbook.Model.FK_Languages", "Languages").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Languages in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Languages> LanguagesReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Languages>("Es.Udc.DotNet.Betbook.Model.FK_Languages", "Languages");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Languages>("Es.Udc.DotNet.Betbook.Model.FK_Languages", "Languages", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Es.Udc.DotNet.Betbook.Model.Favourite in the schema.
    /// </summary>
    /// <KeyProperties>
    /// favouriteId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Es.Udc.DotNet.Betbook.Model", Name="Favourite")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Favourite : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Favourite object.
        /// </summary>
        /// <param name="favouriteId">Initial value of favouriteId.</param>
        /// <param name="date">Initial value of date.</param>
        /// <param name="eventId">Initial value of eventId.</param>
        public static Favourite CreateFavourite(long favouriteId, global::System.DateTime date, long eventId)
        {
            Favourite favourite = new Favourite();
            favourite.favouriteId = favouriteId;
            favourite.date = date;
            favourite.eventId = eventId;
            return favourite;
        }
        /// <summary>
        /// There are no comments for Property favouriteId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long favouriteId
        {
            get
            {
                return this._favouriteId;
            }
            set
            {
                this.OnfavouriteIdChanging(value);
                this.ReportPropertyChanging("favouriteId");
                this._favouriteId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("favouriteId");
                this.OnfavouriteIdChanged();
            }
        }
        private long _favouriteId;
        partial void OnfavouriteIdChanging(long value);
        partial void OnfavouriteIdChanged();
        /// <summary>
        /// There are no comments for Property date in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime date
        {
            get
            {
                return this._date;
            }
            set
            {
                this.OndateChanging(value);
                this.ReportPropertyChanging("date");
                this._date = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("date");
                this.OndateChanged();
            }
        }
        private global::System.DateTime _date;
        partial void OndateChanging(global::System.DateTime value);
        partial void OndateChanged();
        /// <summary>
        /// There are no comments for Property eventId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long eventId
        {
            get
            {
                return this._eventId;
            }
            set
            {
                this.OneventIdChanging(value);
                this.ReportPropertyChanging("eventId");
                this._eventId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("eventId");
                this.OneventIdChanged();
            }
        }
        private long _eventId;
        partial void OneventIdChanging(long value);
        partial void OneventIdChanged();
        /// <summary>
        /// There are no comments for Property name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this.ReportPropertyChanging("name");
                this._name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("name");
                this.OnnameChanged();
            }
        }
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// There are no comments for Property comment in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string comment
        {
            get
            {
                return this._comment;
            }
            set
            {
                this.OncommentChanging(value);
                this.ReportPropertyChanging("comment");
                this._comment = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("comment");
                this.OncommentChanged();
            }
        }
        private string _comment;
        partial void OncommentChanging(string value);
        partial void OncommentChanged();
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.Betbook.Model", "FK_FavouriteUserId", "User")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public User User
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("Es.Udc.DotNet.Betbook.Model.FK_FavouriteUserId", "User").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("Es.Udc.DotNet.Betbook.Model.FK_FavouriteUserId", "User").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<User> UserReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("Es.Udc.DotNet.Betbook.Model.FK_FavouriteUserId", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<User>("Es.Udc.DotNet.Betbook.Model.FK_FavouriteUserId", "User", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Es.Udc.DotNet.Betbook.Model.Group in the schema.
    /// </summary>
    /// <KeyProperties>
    /// groupId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Es.Udc.DotNet.Betbook.Model", Name="Group")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Group : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Group object.
        /// </summary>
        /// <param name="groupId">Initial value of groupId.</param>
        /// <param name="name">Initial value of name.</param>
        public static Group CreateGroup(long groupId, string name)
        {
            Group group = new Group();
            group.groupId = groupId;
            group.name = name;
            return group;
        }
        /// <summary>
        /// There are no comments for Property groupId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long groupId
        {
            get
            {
                return this._groupId;
            }
            set
            {
                this.OngroupIdChanging(value);
                this.ReportPropertyChanging("groupId");
                this._groupId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("groupId");
                this.OngroupIdChanged();
            }
        }
        private long _groupId;
        partial void OngroupIdChanging(long value);
        partial void OngroupIdChanged();
        /// <summary>
        /// There are no comments for Property name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this.ReportPropertyChanging("name");
                this._name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("name");
                this.OnnameChanged();
            }
        }
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// There are no comments for Property description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this._description;
            }
            set
            {
                this.OndescriptionChanging(value);
                this.ReportPropertyChanging("description");
                this._description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("description");
                this.OndescriptionChanged();
            }
        }
        private string _description;
        partial void OndescriptionChanging(string value);
        partial void OndescriptionChanged();
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.Betbook.Model", "FK_GroupCreatorId", "User")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public User User
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("Es.Udc.DotNet.Betbook.Model.FK_GroupCreatorId", "User").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("Es.Udc.DotNet.Betbook.Model.FK_GroupCreatorId", "User").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<User> UserReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("Es.Udc.DotNet.Betbook.Model.FK_GroupCreatorId", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<User>("Es.Udc.DotNet.Betbook.Model.FK_GroupCreatorId", "User", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for User1 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.Betbook.Model", "GroupUsers", "User")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<User> User1
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<User>("Es.Udc.DotNet.Betbook.Model.GroupUsers", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<User>("Es.Udc.DotNet.Betbook.Model.GroupUsers", "User", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Recommendation in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.Betbook.Model", "RecommendationGroups", "Recommendation")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Recommendation> Recommendation
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Recommendation>("Es.Udc.DotNet.Betbook.Model.RecommendationGroups", "Recommendation");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Recommendation>("Es.Udc.DotNet.Betbook.Model.RecommendationGroups", "Recommendation", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Es.Udc.DotNet.Betbook.Model.Languages in the schema.
    /// </summary>
    /// <KeyProperties>
    /// languageCode
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Es.Udc.DotNet.Betbook.Model", Name="Languages")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Languages : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Languages object.
        /// </summary>
        /// <param name="languageCode">Initial value of languageCode.</param>
        /// <param name="languageName">Initial value of languageName.</param>
        public static Languages CreateLanguages(string languageCode, string languageName)
        {
            Languages languages = new Languages();
            languages.languageCode = languageCode;
            languages.languageName = languageName;
            return languages;
        }
        /// <summary>
        /// There are no comments for Property languageCode in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string languageCode
        {
            get
            {
                return this._languageCode;
            }
            set
            {
                this.OnlanguageCodeChanging(value);
                this.ReportPropertyChanging("languageCode");
                this._languageCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("languageCode");
                this.OnlanguageCodeChanged();
            }
        }
        private string _languageCode;
        partial void OnlanguageCodeChanging(string value);
        partial void OnlanguageCodeChanged();
        /// <summary>
        /// There are no comments for Property languageName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string languageName
        {
            get
            {
                return this._languageName;
            }
            set
            {
                this.OnlanguageNameChanging(value);
                this.ReportPropertyChanging("languageName");
                this._languageName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("languageName");
                this.OnlanguageNameChanged();
            }
        }
        private string _languageName;
        partial void OnlanguageNameChanging(string value);
        partial void OnlanguageNameChanged();
        /// <summary>
        /// There are no comments for Countries in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.Betbook.Model", "FK_Languages", "Countries")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Countries> Countries
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Countries>("Es.Udc.DotNet.Betbook.Model.FK_Languages", "Countries");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Countries>("Es.Udc.DotNet.Betbook.Model.FK_Languages", "Countries", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Es.Udc.DotNet.Betbook.Model.Recommendation in the schema.
    /// </summary>
    /// <KeyProperties>
    /// recId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Es.Udc.DotNet.Betbook.Model", Name="Recommendation")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Recommendation : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Recommendation object.
        /// </summary>
        /// <param name="recId">Initial value of recId.</param>
        /// <param name="eventId">Initial value of eventId.</param>
        /// <param name="eventName">Initial value of eventName.</param>
        /// <param name="date">Initial value of date.</param>
        public static Recommendation CreateRecommendation(long recId, long eventId, string eventName, global::System.DateTime date)
        {
            Recommendation recommendation = new Recommendation();
            recommendation.recId = recId;
            recommendation.eventId = eventId;
            recommendation.eventName = eventName;
            recommendation.date = date;
            return recommendation;
        }
        /// <summary>
        /// There are no comments for Property recId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long recId
        {
            get
            {
                return this._recId;
            }
            set
            {
                this.OnrecIdChanging(value);
                this.ReportPropertyChanging("recId");
                this._recId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("recId");
                this.OnrecIdChanged();
            }
        }
        private long _recId;
        partial void OnrecIdChanging(long value);
        partial void OnrecIdChanged();
        /// <summary>
        /// There are no comments for Property eventId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long eventId
        {
            get
            {
                return this._eventId;
            }
            set
            {
                this.OneventIdChanging(value);
                this.ReportPropertyChanging("eventId");
                this._eventId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("eventId");
                this.OneventIdChanged();
            }
        }
        private long _eventId;
        partial void OneventIdChanging(long value);
        partial void OneventIdChanged();
        /// <summary>
        /// There are no comments for Property eventName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string eventName
        {
            get
            {
                return this._eventName;
            }
            set
            {
                this.OneventNameChanging(value);
                this.ReportPropertyChanging("eventName");
                this._eventName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("eventName");
                this.OneventNameChanged();
            }
        }
        private string _eventName;
        partial void OneventNameChanging(string value);
        partial void OneventNameChanged();
        /// <summary>
        /// There are no comments for Property date in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime date
        {
            get
            {
                return this._date;
            }
            set
            {
                this.OndateChanging(value);
                this.ReportPropertyChanging("date");
                this._date = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("date");
                this.OndateChanged();
            }
        }
        private global::System.DateTime _date;
        partial void OndateChanging(global::System.DateTime value);
        partial void OndateChanged();
        /// <summary>
        /// There are no comments for Property text in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string text
        {
            get
            {
                return this._text;
            }
            set
            {
                this.OntextChanging(value);
                this.ReportPropertyChanging("text");
                this._text = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("text");
                this.OntextChanged();
            }
        }
        private string _text;
        partial void OntextChanging(string value);
        partial void OntextChanged();
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.Betbook.Model", "FK_RecommendationUserId", "User")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public User User
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("Es.Udc.DotNet.Betbook.Model.FK_RecommendationUserId", "User").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("Es.Udc.DotNet.Betbook.Model.FK_RecommendationUserId", "User").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<User> UserReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<User>("Es.Udc.DotNet.Betbook.Model.FK_RecommendationUserId", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<User>("Es.Udc.DotNet.Betbook.Model.FK_RecommendationUserId", "User", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Group in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.Betbook.Model", "RecommendationGroups", "Group")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Group> Group
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Group>("Es.Udc.DotNet.Betbook.Model.RecommendationGroups", "Group");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Group>("Es.Udc.DotNet.Betbook.Model.RecommendationGroups", "Group", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Es.Udc.DotNet.Betbook.Model.Tag in the schema.
    /// </summary>
    /// <KeyProperties>
    /// tagId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Es.Udc.DotNet.Betbook.Model", Name="Tag")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Tag : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Tag object.
        /// </summary>
        /// <param name="tagId">Initial value of tagId.</param>
        /// <param name="text">Initial value of text.</param>
        public static Tag CreateTag(long tagId, string text)
        {
            Tag tag = new Tag();
            tag.tagId = tagId;
            tag.text = text;
            return tag;
        }
        /// <summary>
        /// There are no comments for Property tagId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long tagId
        {
            get
            {
                return this._tagId;
            }
            set
            {
                this.OntagIdChanging(value);
                this.ReportPropertyChanging("tagId");
                this._tagId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("tagId");
                this.OntagIdChanged();
            }
        }
        private long _tagId;
        partial void OntagIdChanging(long value);
        partial void OntagIdChanged();
        /// <summary>
        /// There are no comments for Property text in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string text
        {
            get
            {
                return this._text;
            }
            set
            {
                this.OntextChanging(value);
                this.ReportPropertyChanging("text");
                this._text = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("text");
                this.OntextChanged();
            }
        }
        private string _text;
        partial void OntextChanging(string value);
        partial void OntextChanged();
        /// <summary>
        /// There are no comments for Comment in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.Betbook.Model", "CommentTags", "Comment")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Comment> Comment
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Comment>("Es.Udc.DotNet.Betbook.Model.CommentTags", "Comment");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Comment>("Es.Udc.DotNet.Betbook.Model.CommentTags", "Comment", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for Es.Udc.DotNet.Betbook.Model.User in the schema.
    /// </summary>
    /// <KeyProperties>
    /// userId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="Es.Udc.DotNet.Betbook.Model", Name="User")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class User : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="userId">Initial value of userId.</param>
        /// <param name="login">Initial value of login.</param>
        /// <param name="encPassword">Initial value of encPassword.</param>
        /// <param name="name">Initial value of name.</param>
        public static User CreateUser(long userId, string login, string encPassword, string name)
        {
            User user = new User();
            user.userId = userId;
            user.login = login;
            user.encPassword = encPassword;
            user.name = name;
            return user;
        }
        /// <summary>
        /// There are no comments for Property userId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long userId
        {
            get
            {
                return this._userId;
            }
            set
            {
                this.OnuserIdChanging(value);
                this.ReportPropertyChanging("userId");
                this._userId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("userId");
                this.OnuserIdChanged();
            }
        }
        private long _userId;
        partial void OnuserIdChanging(long value);
        partial void OnuserIdChanged();
        /// <summary>
        /// There are no comments for Property login in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string login
        {
            get
            {
                return this._login;
            }
            set
            {
                this.OnloginChanging(value);
                this.ReportPropertyChanging("login");
                this._login = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("login");
                this.OnloginChanged();
            }
        }
        private string _login;
        partial void OnloginChanging(string value);
        partial void OnloginChanged();
        /// <summary>
        /// There are no comments for Property encPassword in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string encPassword
        {
            get
            {
                return this._encPassword;
            }
            set
            {
                this.OnencPasswordChanging(value);
                this.ReportPropertyChanging("encPassword");
                this._encPassword = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("encPassword");
                this.OnencPasswordChanged();
            }
        }
        private string _encPassword;
        partial void OnencPasswordChanging(string value);
        partial void OnencPasswordChanged();
        /// <summary>
        /// There are no comments for Property name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this.ReportPropertyChanging("name");
                this._name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("name");
                this.OnnameChanged();
            }
        }
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// There are no comments for Property surname in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string surname
        {
            get
            {
                return this._surname;
            }
            set
            {
                this.OnsurnameChanging(value);
                this.ReportPropertyChanging("surname");
                this._surname = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("surname");
                this.OnsurnameChanged();
            }
        }
        private string _surname;
        partial void OnsurnameChanging(string value);
        partial void OnsurnameChanged();
        /// <summary>
        /// There are no comments for Property email in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string email
        {
            get
            {
                return this._email;
            }
            set
            {
                this.OnemailChanging(value);
                this.ReportPropertyChanging("email");
                this._email = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("email");
                this.OnemailChanged();
            }
        }
        private string _email;
        partial void OnemailChanging(string value);
        partial void OnemailChanged();
        /// <summary>
        /// There are no comments for Property countryCode in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string countryCode
        {
            get
            {
                return this._countryCode;
            }
            set
            {
                this.OncountryCodeChanging(value);
                this.ReportPropertyChanging("countryCode");
                this._countryCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("countryCode");
                this.OncountryCodeChanged();
            }
        }
        private string _countryCode;
        partial void OncountryCodeChanging(string value);
        partial void OncountryCodeChanged();
        /// <summary>
        /// There are no comments for Property languageCode in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string languageCode
        {
            get
            {
                return this._languageCode;
            }
            set
            {
                this.OnlanguageCodeChanging(value);
                this.ReportPropertyChanging("languageCode");
                this._languageCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("languageCode");
                this.OnlanguageCodeChanged();
            }
        }
        private string _languageCode;
        partial void OnlanguageCodeChanging(string value);
        partial void OnlanguageCodeChanged();
        /// <summary>
        /// There are no comments for Comment in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.Betbook.Model", "FK_CommentUserId", "Comment")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Comment> Comment
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Comment>("Es.Udc.DotNet.Betbook.Model.FK_CommentUserId", "Comment");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Comment>("Es.Udc.DotNet.Betbook.Model.FK_CommentUserId", "Comment", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Favourite in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.Betbook.Model", "FK_FavouriteUserId", "Favourite")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Favourite> Favourite
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Favourite>("Es.Udc.DotNet.Betbook.Model.FK_FavouriteUserId", "Favourite");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Favourite>("Es.Udc.DotNet.Betbook.Model.FK_FavouriteUserId", "Favourite", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Group in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.Betbook.Model", "FK_GroupCreatorId", "Group")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Group> Group
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Group>("Es.Udc.DotNet.Betbook.Model.FK_GroupCreatorId", "Group");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Group>("Es.Udc.DotNet.Betbook.Model.FK_GroupCreatorId", "Group", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Recommendation in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.Betbook.Model", "FK_RecommendationUserId", "Recommendation")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Recommendation> Recommendation
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Recommendation>("Es.Udc.DotNet.Betbook.Model.FK_RecommendationUserId", "Recommendation");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Recommendation>("Es.Udc.DotNet.Betbook.Model.FK_RecommendationUserId", "Recommendation", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Group1 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("Es.Udc.DotNet.Betbook.Model", "GroupUsers", "Group")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Group> Group1
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Group>("Es.Udc.DotNet.Betbook.Model.GroupUsers", "Group");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Group>("Es.Udc.DotNet.Betbook.Model.GroupUsers", "Group", value);
                }
            }
        }
    }
}
